name: Issue Report
description: Create an issue report for Assisty.
title: "BUG | "
labels: ["bug"]
projects: ["Assisty-Feedback/main"]
body:
  - type: input
    id: username
    attributes:
      label: Discord Username
      description: This will be used if we require any additional information on the issue.
      placeholder: ex. Kaosdiy
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version did this issue occur in?
      description: Can be found using the /help command.
      placeholder: "0.0.0"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Describe the issue in detail.
      description: This could be reproduction steps or a better description of what is happening (ideally, please provide both if possible).
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: Provide some images / videos of the issue in action.
    validations:
      required: true
  - type: checkboxes
    id: confirmation
    attributes:
      label: Before Submitting
      description: Please check the boxes below before submitting.
      options:
        - label: I have confirmed that nobody else reported this issue.
          required: true
        - label: The details of this report are legitimate.
          required: true
        - label: I understand that i may be messaged if further information is needed.
          required: true
